---
cassandra_packages:
  - dse-full
  - dse
  - dse-hive
  - dse-pig
  - dse-demos
  - dse-libsolr
  - dse-libtomcat
  - dse-libsqoop
  - dse-liblog4j
  - dse-libmahout
  - dse-libhadoop-native
  - dse-libcassandra
  - dse-libhive
  - dse-libpig
  - dse-libhadoop
  - datastax-agent
  - sysstat
